### ISSUE TITLE
problem intel hd graphics

### ISSUE THREAD

**Issue by mkultimate** [Nezarn/ABCShaderfix#1]
presents this problem with the intel hd video

![image](https://user-images.githubusercontent.com/16367065/41830735-539dab26-7808-11e8-80f5-f74f18b7fa17.png)

**Comment by Nezarn** [comment]
Intel GPUs doesn't support nvidia specific shaders like AMD, so obviously it will never work.

I recommend buying an nvidia or AMD card.
